server:
  port: 8767
spring:
  profiles:
    include: quartmemory
  application:
    name: carrot-user
  datasource:
    url: jdbc:mysql://localhost:3306/carrot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  type-aliases-package: com.mmd.carrotorder.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
        #驼峰下划线转换
      column-underline: true
        #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
#  type-aliases-package: com.mmd.carrotorder.entity
# 控制台打印sql
logging:
  level:
    com:
      mmd:
        carrotorder:
          mapper: debug
