#spring:
#  application:
#    name: carrot-getway

#      cloud:
#        gateway:
#          routes:
#            # This route rule used to forward request to activity server
#              - id: user-route
#              uri: lb://carrot-user
#              predicates:
#                - Path=/user/**
#              filters:
#              #设置StripPrefix=1表示从二级url路径转发，即http://localhost:port/activity/test将会转发到http://{activity}/test
#                - StripPrefix=1
#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true #使用小写service-id



server:
  port: 8763


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#zuul:
#  routes:
#    api-a:
#      path: /api/a/**
#      serviceId: carrot-user
#    api-b:
#      path: /api/b/**
spring:
  application:
    name: carrot-getway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: carrot-user
          uri: lb://carrot-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0
        - id: carrot-mail
          uri: lb://carrot-mail
          predicates:
            - Path=/mail/**
          filters:
            - StripPrefix=0



