spring:
  application:
    name: carrot-mail
  mail:
    #host需要服务器能连到
    host: 127.0.0.1
    username: xxxx
    password: xxxx
    default-encoding: utf-8

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mail:
  fromMail:
    addr: xxxx@163.com
